### ISSUE TITLE
missing gflags/gflags.h file

### ISSUE THREAD

**Issue by ianbstewart** [ikekonglp/TweeboParser#12]
When I try to run `install.sh` the installation breaks due to the following error:

```
../classifier/Options.h:24:10: fatal error: 'gflags/gflags.h' file not found
```

Is there a missing `gflags/gflags.h` file?

**Comment by printfoo** [comment]
I had the same issue. It turns out I didn't have [cmake](https://cmake.org/install).

**Comment by ianbstewart** [comment]
I do have `cmake` installed, so I don't think that's the issue. I'm going to close this because it solved itself and was replaced with a much bigger bug.
