### ISSUE TITLE
Change the way the pretrained_models.tar.gz is handled

### ISSUE THREAD

**Issue by Liebeck** [ikekonglp/TweeboParser#2]
Hi, thanks for providing TweeboParser. I'd like to offer two suggestions for the install.sh and the handling of the pretrained_models.tar.gz because the download time from your server can take up to 10 minutes, even with a 700 MBit/s internet connection.
1. Please add an optional parameter that skips "rm pretrained_models.tar.gz" if the parameter is set. In our case, we could use a cached copy of the models but still want the latest TweeboParser from GitHub.
2. Allow another optional parameter for an alternative mirror for the curl call.

**Comment by Liebeck** [comment]
The official download server seems to be slow today. A colleague of mine is downloading the models for more than 10 hours and it hasn't finished yet. Are you able to reset the server or something like that? ;)

**Comment by ikekonglp** [comment]
Hi Liebeck,

Sorry for the late reply. I have added that into the installation script.
