### ISSUE TITLE
Include a script to convert CoNLL output to standoff format for use with brat visualizer.

### ISSUE THREAD

**Issue by arunchaganty** [ikekonglp/TweeboParser#3]
It would be convenient if the output produced by the TweeboParser could be visualized using the [brat annotation tool](http://brat.nlplab.org/standoff.html). To do so, one needs to convert the CoNLL-ish output produced by Tweebo to the [standoff format](http://brat.nlplab.org/standoff.html). 

Unfortunately, the Tweebo output is slightly non-standard CoNLL and hence breaks brat's own conversion tools. 

The attached file contains a python script that performs the conversion as well as configuration files to use with Brat.

[tweebo-brat.zip](https://github.com/ikekonglp/TweeboParser/files/271749/tweebo-brat.zip)

**Comment by ikekonglp** [comment]
Thanks Arun! That helps a lot!
